#!/usr/bin/env sh

#ddev-generated
## Description: Run redis-cli inside the Dragonfly container
## Usage: dragonfly-cli [flags] [args]
## Example: "ddev dragonfly-cli KEYS *" or "ddev dragonfly-cli INFO" or "ddev dragonfly-cli --version"
## Aliases: redis-cli

# Dragonfly is Redis-compatible, just connect directly
redis-cli -p 6379 -h dragonfly $@
